apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: core-services
  sources:
    - repoURL: https://github.com/QumulusTechnology/argocd-demo.git
      targetRevision: main
      ref: vals

    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 5.42.1
      chart: loki
      helm:
        valueFiles:
          - $vals/services/loki/values.yaml
        valuesObject:
          ingress:
            hosts:
              - loki.{{ .Values.domain }}
            tls:
              - secretName: loki-tls
                hosts:
                  - loki.{{ .Values.domain }}
          gateway:
            ingress:
              hosts:
                - host: gateway-loki.{{ .Values.domain }}
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - secretName: loki-gateway-tls
                  hosts:
                    - gateway-loki.{{ .Values.domain }}

    - repoURL: https://charts.bitnami.com/bitnami
      chart: memcached
      targetRevision: 6.7.0
      helm:
        releaseName: chunk-cache
        valueFiles:
          - $vals/services/loki/memcached-chunk-values.yaml

    - repoURL: https://charts.bitnami.com/bitnami
      chart: memcached
      targetRevision: 6.7.0
      helm:
        releaseName: results-cache
        valueFiles:
          - $vals/services/loki/memcached-results-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
