apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ClusterIssuer
      name: letsencrypt
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: email@newdomain.com
